# This workflow will automatically deploy your application to www.evennode.com on push to main branch.

name: Deploy to EvenNode

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.MIIEowIBAAKCAQEA2gjrBpl/oLumCfA0oO32+/igMMlzEjB5AvqMlNfniukl0GohzJuc5CLo1SqyQSkezqR4qGlLIhFJD3CHOjEVt8wn3ibEvMxQ4xDJRWRYvLjE7aSSfNj7r3v3Kz2v2Y2oZL0LiaQ8YLdIOEKn5/stDpTLJdqhLrxswvrbSWMImK5sKpC2GObbPXvlbvPMSauE1R1gFh19n87X0fqu7ZWhnN3PcLfGVB77ifhRjmLlVhWfTtizcj/vAAB1AgdsXowGBUz2xvKk4zr7JTVGiCEcIKS02tcBzPVUdMmP3ESpa6hf+DrqQVwJf3pvGLihTBJzhfRGa4YW1kr1NFxc4ZmvGQIDAQABAoIBADQ+BMptByalL7Cb7JBO1GoldYSbEEZgdO5gyER1wxYGrTfV5klXU+1Z6/3/n/x69NXAlOSNbiI4kA/x/4TS9Ag5E6hoE6XFMvBlOkS1OYnmn9DtKOhfOVcf1eZ3fmYbSijxHw2Y25q078oDNqYgCfi/cDmevBYtscW6Q8a+wvWKDDY5n+yx3XTKEzi6A0ubCdu8cwUmMClBIDfY2Ga0n3knbW88F60NBfz0qa1ghuFEr6d58LRm0Y2LUgDuEoNt/fxf8nn1B3MK9YuHYF5X6qZJOURLh8C7q4uKlYMPpeOTthLomO86RYqzjIQdxBmONQPXOVHMau8d4Gg5hghXbnECgYEA9WFi8P+derYtP4Im9p4cRpyCz3cqc8KL4goGyfSyYgCAtkuXsRU6cqC80fsGrUnpJ2BAtVU40JrtB2TBUZI8jTi9XhR9B0DoDdkTRerFn4VSGalZp4ULGWkARCW9Cn241n9OmqYU/ScYRnBF2jvgWNmbc/EfmWEUgqCZgt7kenUCgYEA43iQpJHhaa4Q8UuUaTLh0xV/zMznLnTa3DPkLLYHv0OQnwcSLaX6o/lHple0o+Bb/euqdeZCP8KnrN1LASmFQ4QhJg8EeA4s5k/Z4ZyWJMf+cW8RZVzGgc/v8sm7TQmoGsil85CYkKhg/28j2mSW4K8dUKTKm9qBAdfLCATNpZUCgYAnjKnI1DpKpABJAy5Kg5NlIibHT5qtC8dGCH2toV37A7+7IhXx+czw2s10PrSFy6rjqNTlJTZCESZxEaFDB4Hw9Rs4ha7dM23zhXBgzYVKv89KyYvkv0HZt53OXhLJFRhsohpGPMyXPOzhtYjcstfnGjO/DTcdnpMSttXnTQugXQKBgQCLpbbW8aA7KtvH5yiDtPMija5Z4umCgcbjLRBFyrLS3v3oQ4ULdTx8cktkea+yc8jGCGor22KMlkouO+USH5Vqr7FSFiIeOkWiVx9h/KnIhudUaGV7nwtXInsiyGouj2EeoFQRRZIELPrvliGir+JYqekLWz/vkqNkqEBC+f/uSQKBgD5DrzyYzBRW8qnOOjypR3ELLfV7IbXrg+5cPydHvyy/bfrRzEMzr4d+rtmV9HFYO3vPatDZUhaacp3ymTf78YT5CLxuUhr+J6UN4Xsw4j3Fhmg3w2bp7yKxNe9TZA6VtK9p8uEp3AXfS//bHr0Fw1BaiUFDVIj9+1tIkRPtEMC2
        known_hosts: " "
    - name: Add git.evennode.com to known_hosts
      run: |
        ssh-keyscan -H git.evennode.com > ~/.ssh/known_hosts
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Deploy to evennode.com
      run: |
        git remote add evennode ${{ secrets.git@git.evennode.com:ff44fafb6b0c48bf7fea2005dda97484.git }}
        git config --global user.email "${{ secrets.amitlumarshah499@gmail.com }}"
        git config --global user.name "${{ secrets.Abhishek }}"
        git push evennode +main
